#Robot Properties
#Sun Aug 20 21:16:04 EST 2006
robot.description=\         Robot with 2 modes possibles: \n          1 Random with 2 subclasses & 1 with Attack or Defensive mode\n\n                     Acts by setted strategist (Interface IStrategist)
robot.webpage=
robocode.version=1.1.2
robot.java.source.included=true
robot.author.name=Juan Volpe & Sol Castro
robot.classname=jvolpecastro.Renault12
robot.name=Renault12
