#Robocode Compiler Properties
#Mon Sep 01 22:35:01 GMT-03:00 2025
compiler.binary=
compiler.classpath=-classpath libs\\robocode.jar;"C\:\\Users\\juan_\\IdeaProjects\\Laboratorio de Software\\P2\\RobocodeLabo\\robots"
compiler.options=
robocode.version=1.10.0
