#Robocode window sizes
#Fri Sep 05 18:35:17 GMT-03:00 2025
net.sf.robocode.ui.dialog.NewBattleDialog=511,26,850,645
net.sf.robocode.ui.dialog.PreferencesDialog=449,305,1022,424
net.sf.robocode.ui.dialog.RobocodeFrame=0,0,927,701
