#Robocode window sizes
#Sat Oct 18 18:59:01 GMT-03:00 2025
=\=\=\=\=\=\=
<<<<<<<=Updated upstream
>>>>>>>=Stashed changes
net.sf.robocode.ui.dialog.NewBattleDialog=511,26,850,645
net.sf.robocode.ui.dialog.PreferencesDialog=449,305,1022,424
net.sf.robocode.ui.dialog.RobocodeFrame=0,0,927,701
net.sf.robocode.ui.packager.RobotPackager=460,187,616,490
