#Robot Properties
#Sun Aug 20 21:16:04 EST 2006
robot.description=\                             A sample particular robot intent ML simulation\n\n                     Acts by extern impulses 
robot.webpage=
robocode.version=1.1.2
robot.java.source.included=true
robot.author.name=Juan Volpe
robot.classname=my-samples.AdaptiveRobot
robot.name=Adaptive robot
